### ISSUE TITLE
Normalize node['osl-php']['packages'] to be agnostic to PHP versions 

### ISSUE THREAD

**Issue by ramereth** [osuosl-cookbooks/osl-php#14]
Right now most of the php packages in IUS have versions prefixed in them (i.e. php56u for 5.6 and php71u for php 7.1). That means we have to maintain two different lists of packages based on versions which is sub optimal.

I recommend we change it so that this attribute just has the names of the packages after the prefix and then we add logic to add the prefix and then set them in ``node['php']['packages']``. In most cases, the names of the packages remain the same between php versions (with a few exceptions).

So for example:

- Given we want to install ``php56u-gd``, we'd just add ``gd`` to ``node['osl-php']['packages'] `` and also set ``node['php']['version'] = '5.6'``
- The code in ``osl-php::packages`` will then look at the value of the ``node['php']['version']`` attribute and then prepend ``php56u-`` to ``gd`` and add it as ``php56u-gd`` to ``node['php']['packages']``.

We would want to add support for all of the current versions of php we have deployed.

For backwards compatibility we could check to see if the name has already been prepended based on a regular expression and then just bypass the logic. Or we could just fix every reference we have already to make this more simple and deploy it at once.

**Comment by TravisWhitehead** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [phpBB: PHP 7 Upgrade](https://trello.com/c/jVbH3DSB/226-phpbb-php-7-upgrade)

**Comment by ramereth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Normalize node['osl-php']['packages'] to be agnostic to PHP versions](https://trello.com/c/MTPvYYSy/615-normalize-nodeosl-phppackages-to-be-agnostic-to-php-versions)
